name: Mackubin Street Coffee and Kitchen
favicon: null
layout_spectrum: 0.8181277341209352
typography_spectrum: 0.8636259669438004
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#000000'
    - '#a1a9ac'
    - '#5a5a58'
    - '#048d98'
  brandStrength: 0.75
  lightness: 0.40063406294211745
  saturation: 0.23535147472284734
  rhythmicContrast: 0.22378344112075865
purpose: []
